// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbLvrAtuPU1kh6decIixPWhxaBN1LudXM',
    appId: '1:608820582627:web:92c2cae659a466d2a24dd6',
    messagingSenderId: '608820582627',
    projectId: 'greenland-df555',
    authDomain: 'greenland-df555.firebaseapp.com',
    storageBucket: 'greenland-df555.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPeDMQE6tN7vqWimZX6JB3i49S3IXN9fc',
    appId: '1:608820582627:android:5202bff16f9ea512a24dd6',
    messagingSenderId: '608820582627',
    projectId: 'greenland-df555',
    storageBucket: 'greenland-df555.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSPD-7MO9YV3M0R5q4HvBLpX6pceyTWqU',
    appId: '1:608820582627:ios:ed248fe92b64d16fa24dd6',
    messagingSenderId: '608820582627',
    projectId: 'greenland-df555',
    storageBucket: 'greenland-df555.appspot.com',
    iosBundleId: 'com.example.greenland',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSPD-7MO9YV3M0R5q4HvBLpX6pceyTWqU',
    appId: '1:608820582627:ios:b05e420634f555c3a24dd6',
    messagingSenderId: '608820582627',
    projectId: 'greenland-df555',
    storageBucket: 'greenland-df555.appspot.com',
    iosBundleId: 'com.example.greenland.RunnerTests',
  );
}
